// src/App.jsx
import SideBar from "./lib/components/SideBar";
import { v4 as uuidv4 } from "uuid";
import  theme from "./lib/theme/index";

const icons = {
  Customers: (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className="w-5 h-5 opacity-75"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth="2"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
      />
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
      />
    </svg>
  ),
  SMS: (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className="w-5 h-5 opacity-75"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth="2"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"
      />
    </svg>
  ),
  Settings: (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className="w-5 h-5 opacity-75"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth="2"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
      />
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
      />
    </svg>
  ),
};

const Menus = [
  {
    id: uuidv4(),
    name: "Customers",
    active: false,
    onClickHandler: () => {},
    items: [
      {
        id: uuidv4(),
        name: "sub-item-1",
        active: false,
        onClickHandler: () => {},
      },
    ],
  },
  {
    id: uuidv4(),
    name: "SMS",
    active: false,
    onClickHandler: () => {},
    items: [
      {
        id: uuidv4(),
        name: "Inbox",
        active: false,
        onClickHandler: () => {},
      },
      {
        id: uuidv4(),
        name: "OutBox",
        active: false,
        onClickHandler: () => {},
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Settings",
    active: false,
    onClickHandler: () => {},
    items: [],
  },
];

function App() {
  return (
    <div>
      <SideBar menus={Menus} icons={icons} />
    </div>
  );
}

export default App;

// src/App.vue
<script setup>
import { v4 as uuidv4 } from "uuid";
import SideBar from './lib/components/navigation/SideBar.vue';

const Menus = [
  {
    id: uuidv4(),
    name: "Customers",
    active: false,
    onClickHandler: () => {},
    items: [
      {
        id: uuidv4(),
        name: "sub-item-1",
        active: false,
        onClickHandler: () => {},
      },
    ],
    icon: "users",
  },
  {
    id: uuidv4(),
    name: "SMS",
    active: false,
    onClickHandler: () => {},
    items: [
      {
        id: uuidv4(),
        name: "Inbox",
        active: false,
        onClickHandler: () => {},
      },
      {
        id: uuidv4(),
        name: "OutBox",
        active: false,
        onClickHandler: () => {},
      },
    ],
    icon: "send",
  },
  {
    id: uuidv4(),
    name: "Settings",
    active: false,
    onClickHandler: () => {},
    items: [],
    icon: "settings",
  },
];

</script>

<template>
  <div>
    <SideBar :menus="Menus" />
    
  </div>
</template>


<style>
@import url('./index.css');
</style>
